2025-07-13 21:09:17,817 - INFO - Loaded command: coinflip.py
2025-07-13 21:09:17,820 - INFO - Loaded command: ouroboros.py
2025-07-13 21:09:17,857 - INFO - Loaded command: rpsgame.py
2025-07-13 21:09:17,862 - INFO - Loaded command: rpsvs.py
2025-07-13 21:09:17,866 - INFO - Loaded command: sporty.py
2025-07-13 21:09:17,870 - INFO - Loaded command: update.py
2025-07-13 21:09:17,885 - INFO - Loaded cog: channelmanagement.py
2025-07-13 21:09:17,888 - INFO - Loaded cog: embed.py
2025-07-13 21:09:17,917 - INFO - Loaded cog: finance.py
2025-07-13 21:09:18,081 - INFO - Loaded cog: leaderboard.py
2025-07-13 21:09:19,500 - INFO - Loaded cog: leveling.py
2025-07-13 21:09:19,768 - INFO - Loaded cog: movies.py
2025-07-13 21:09:19,911 - INFO - Loaded cog: notification.py
2025-07-13 21:09:19,918 - INFO - Loaded cog: serverstat.py
2025-07-13 21:09:19,924 - INFO - Loaded cog: tournaments.py
2025-07-13 21:09:19,928 - INFO - Loaded cog: welcome.py
2025-07-13 21:09:19,929 - INFO - Loaded commands and cogs
2025-07-13 21:09:20,179 - INFO - Slash commands synced successfully: 33 commands
2025-07-13 21:09:22,476 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-13 21:10:54.459724:
no such table: leaderboard_1221132104876687511
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\leaderboard.py", line 115, in leaderboard
    c.execute(
sqlite3.OperationalError: no such table: leaderboard_1221132104876687511

2025-07-13 21:10:54,460 - ERROR - Exception occurred on 2025-07-13 21:10:54.459724:
no such table: leaderboard_1221132104876687511
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\leaderboard.py", line 115, in leaderboard
    c.execute(
sqlite3.OperationalError: no such table: leaderboard_1221132104876687511

2025-07-13 21:14:07,868 - INFO - Loaded command: coinflip.py
2025-07-13 21:14:07,876 - INFO - Loaded command: ouroboros.py
2025-07-13 21:14:07,899 - INFO - Loaded command: rpsgame.py
2025-07-13 21:14:07,903 - INFO - Loaded command: rpsvs.py
2025-07-13 21:14:07,909 - INFO - Loaded command: sporty.py
2025-07-13 21:14:07,913 - INFO - Loaded command: update.py
2025-07-13 21:14:07,923 - INFO - Loaded cog: channelmanagement.py
2025-07-13 21:14:07,929 - INFO - Loaded cog: embed.py
2025-07-13 21:14:08,017 - INFO - Loaded cog: finance.py
2025-07-13 21:14:08,107 - INFO - Loaded cog: leaderboard.py
2025-07-13 21:14:09,474 - INFO - Loaded cog: leveling.py
2025-07-13 21:14:09,674 - INFO - Loaded cog: movies.py
2025-07-13 21:14:09,794 - INFO - Loaded cog: notification.py
2025-07-13 21:14:09,800 - INFO - Loaded cog: serverstat.py
2025-07-13 21:14:09,806 - INFO - Loaded cog: tournaments.py
2025-07-13 21:14:09,811 - INFO - Loaded cog: welcome.py
2025-07-13 21:14:09,812 - INFO - Loaded commands and cogs
2025-07-13 21:14:10,009 - INFO - Slash commands synced successfully: 33 commands
2025-07-13 21:14:12,262 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-13 21:14:12.426529:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:14:12,540 - ERROR - Exception occurred on 2025-07-13 21:14:12.426529:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:14:12.698474:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:14:12,700 - ERROR - Exception occurred on 2025-07-13 21:14:12.698474:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:14:12.843833:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:14:12,845 - ERROR - Exception occurred on 2025-07-13 21:14:12.843833:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:14:13.059684:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:14:13,062 - ERROR - Exception occurred on 2025-07-13 21:14:13.059684:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:14:13.338655:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:14:13,340 - ERROR - Exception occurred on 2025-07-13 21:14:13.338655:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:14:13.510670:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:14:13,511 - ERROR - Exception occurred on 2025-07-13 21:14:13.510670:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:21:22,336 - INFO - Loaded command: coinflip.py
2025-07-13 21:21:22,339 - INFO - Loaded command: ouroboros.py
2025-07-13 21:21:22,352 - INFO - Loaded command: rpsgame.py
2025-07-13 21:21:22,355 - INFO - Loaded command: rpsvs.py
2025-07-13 21:21:22,358 - INFO - Loaded command: sporty.py
2025-07-13 21:21:22,362 - INFO - Loaded command: update.py
2025-07-13 21:21:22,368 - INFO - Loaded cog: channelmanagement.py
2025-07-13 21:21:22,371 - INFO - Loaded cog: embed.py
2025-07-13 21:21:22,393 - INFO - Loaded cog: finance.py
2025-07-13 21:21:22,441 - INFO - Loaded cog: leaderboard.py
2025-07-13 21:21:23,533 - INFO - Loaded cog: leveling.py
2025-07-13 21:21:23,727 - INFO - Loaded cog: movies.py
2025-07-13 21:21:23,811 - INFO - Loaded cog: notification.py
2025-07-13 21:21:23,816 - INFO - Loaded cog: serverstat.py
2025-07-13 21:21:23,821 - INFO - Loaded cog: tournaments.py
2025-07-13 21:21:23,824 - INFO - Loaded cog: welcome.py
2025-07-13 21:21:23,825 - INFO - Loaded commands and cogs
2025-07-13 21:21:24,139 - INFO - Slash commands synced successfully: 33 commands
2025-07-13 21:21:26,411 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-13 21:21:26.628527:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:21:26,635 - ERROR - Exception occurred on 2025-07-13 21:21:26.628527:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:21:26.815374:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:21:26,817 - ERROR - Exception occurred on 2025-07-13 21:21:26.815374:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:21:27.131682:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:21:27,135 - ERROR - Exception occurred on 2025-07-13 21:21:27.131682:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:21:27.313999:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:21:27,317 - ERROR - Exception occurred on 2025-07-13 21:21:27.313999:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:21:27.474627:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:21:27,476 - ERROR - Exception occurred on 2025-07-13 21:21:27.474627:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:21:27.677768:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:21:27,679 - ERROR - Exception occurred on 2025-07-13 21:21:27.677768:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:23:40,636 - INFO - Loaded command: coinflip.py
2025-07-13 21:23:40,639 - INFO - Loaded command: ouroboros.py
2025-07-13 21:23:40,653 - INFO - Loaded command: rpsgame.py
2025-07-13 21:23:40,655 - INFO - Loaded command: rpsvs.py
2025-07-13 21:23:40,659 - INFO - Loaded command: sporty.py
2025-07-13 21:23:40,662 - INFO - Loaded command: update.py
2025-07-13 21:23:40,669 - INFO - Loaded cog: channelmanagement.py
2025-07-13 21:23:40,673 - INFO - Loaded cog: embed.py
2025-07-13 21:23:40,697 - INFO - Loaded cog: finance.py
2025-07-13 21:23:40,750 - INFO - Loaded cog: leaderboard.py
2025-07-13 21:23:42,078 - INFO - Loaded cog: leveling.py
2025-07-13 21:23:42,295 - INFO - Loaded cog: movies.py
2025-07-13 21:23:42,384 - INFO - Loaded cog: notification.py
2025-07-13 21:23:42,389 - INFO - Loaded cog: serverstat.py
2025-07-13 21:23:42,393 - INFO - Loaded cog: tournaments.py
2025-07-13 21:23:42,395 - INFO - Loaded cog: welcome.py
2025-07-13 21:23:42,396 - INFO - Loaded commands and cogs
2025-07-13 21:23:42,687 - INFO - Slash commands synced successfully: 33 commands
2025-07-13 21:23:45,030 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-13 21:23:45.164477:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:23:45,170 - ERROR - Exception occurred on 2025-07-13 21:23:45.164477:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:23:45.318184:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:23:45,319 - ERROR - Exception occurred on 2025-07-13 21:23:45.318184:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:23:45.480985:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:23:45,482 - ERROR - Exception occurred on 2025-07-13 21:23:45.480985:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:23:45.652959:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:23:45,656 - ERROR - Exception occurred on 2025-07-13 21:23:45.652959:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:23:45.809691:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:23:45,810 - ERROR - Exception occurred on 2025-07-13 21:23:45.809691:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:23:45.975403:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:23:45,976 - ERROR - Exception occurred on 2025-07-13 21:23:45.975403:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:29:13,664 - INFO - Loaded command: coinflip.py
2025-07-13 21:29:13,667 - INFO - Loaded command: ouroboros.py
2025-07-13 21:29:13,680 - INFO - Loaded command: rpsgame.py
2025-07-13 21:29:13,683 - INFO - Loaded command: rpsvs.py
2025-07-13 21:29:13,685 - INFO - Loaded command: sporty.py
2025-07-13 21:29:13,688 - INFO - Loaded command: update.py
2025-07-13 21:29:13,694 - INFO - Loaded cog: channelmanagement.py
2025-07-13 21:29:13,698 - INFO - Loaded cog: embed.py
2025-07-13 21:29:13,720 - INFO - Loaded cog: finance.py
2025-07-13 21:29:13,775 - INFO - Loaded cog: leaderboard.py
2025-07-13 21:29:15,225 - INFO - Loaded cog: leveling.py
2025-07-13 21:29:15,538 - INFO - Loaded cog: movies.py
2025-07-13 21:29:15,646 - INFO - Loaded cog: notification.py
2025-07-13 21:29:15,651 - INFO - Loaded cog: serverstat.py
2025-07-13 21:29:15,657 - INFO - Loaded cog: tournaments.py
2025-07-13 21:29:15,664 - INFO - Loaded cog: welcome.py
2025-07-13 21:29:15,665 - INFO - Loaded commands and cogs
2025-07-13 21:29:15,894 - INFO - Slash commands synced successfully: 33 commands
2025-07-13 21:29:18,226 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-13 21:29:18.360670:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:29:18,366 - ERROR - Exception occurred on 2025-07-13 21:29:18.360670:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:29:18.505529:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:29:18,508 - ERROR - Exception occurred on 2025-07-13 21:29:18.505529:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:29:18.656423:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:29:18,658 - ERROR - Exception occurred on 2025-07-13 21:29:18.656423:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:29:18.859619:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:29:18,863 - ERROR - Exception occurred on 2025-07-13 21:29:18.859619:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:29:19.099068:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:29:19,101 - ERROR - Exception occurred on 2025-07-13 21:29:19.099068:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:29:19.332710:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:29:19,334 - ERROR - Exception occurred on 2025-07-13 21:29:19.332710:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:34:31,752 - INFO - Loaded command: coinflip.py
2025-07-13 21:34:31,755 - INFO - Loaded command: ouroboros.py
2025-07-13 21:34:31,769 - INFO - Loaded command: rpsgame.py
2025-07-13 21:34:31,772 - INFO - Loaded command: rpsvs.py
2025-07-13 21:34:31,774 - INFO - Loaded command: sporty.py
2025-07-13 21:34:31,777 - INFO - Loaded command: update.py
2025-07-13 21:34:31,785 - INFO - Loaded cog: channelmanagement.py
2025-07-13 21:34:31,788 - INFO - Loaded cog: embed.py
2025-07-13 21:34:31,815 - INFO - Loaded cog: finance.py
2025-07-13 21:34:31,874 - INFO - Loaded cog: leaderboard.py
2025-07-13 21:34:33,327 - INFO - Loaded cog: leveling.py
2025-07-13 21:34:33,532 - INFO - Loaded cog: movies.py
2025-07-13 21:34:33,621 - INFO - Loaded cog: notification.py
2025-07-13 21:34:33,626 - INFO - Loaded cog: serverstat.py
2025-07-13 21:34:33,631 - INFO - Loaded cog: tournaments.py
2025-07-13 21:34:33,635 - INFO - Loaded cog: welcome.py
2025-07-13 21:34:33,635 - INFO - Loaded commands and cogs
2025-07-13 21:34:34,031 - INFO - Slash commands synced successfully: 33 commands
2025-07-13 21:34:36,305 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-13 21:34:36.477124:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:34:36,484 - ERROR - Exception occurred on 2025-07-13 21:34:36.477124:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:34:36.706204:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:34:36,709 - ERROR - Exception occurred on 2025-07-13 21:34:36.706204:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:34:36.847681:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:34:36,850 - ERROR - Exception occurred on 2025-07-13 21:34:36.847681:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:34:37.070551:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:34:37,074 - ERROR - Exception occurred on 2025-07-13 21:34:37.070551:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:34:37.319257:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:34:37,321 - ERROR - Exception occurred on 2025-07-13 21:34:37.319257:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:34:37.565335:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:34:37,566 - ERROR - Exception occurred on 2025-07-13 21:34:37.565335:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:36:09,390 - INFO - Loaded command: coinflip.py
2025-07-13 21:36:09,392 - INFO - Loaded command: ouroboros.py
2025-07-13 21:36:09,407 - INFO - Loaded command: rpsgame.py
2025-07-13 21:36:09,411 - INFO - Loaded command: rpsvs.py
2025-07-13 21:36:09,414 - INFO - Loaded command: sporty.py
2025-07-13 21:36:09,419 - INFO - Loaded command: update.py
2025-07-13 21:36:09,427 - INFO - Loaded cog: channelmanagement.py
2025-07-13 21:36:09,430 - INFO - Loaded cog: embed.py
2025-07-13 21:36:09,495 - INFO - Loaded cog: finance.py
2025-07-13 21:36:09,611 - INFO - Loaded cog: leaderboard.py
2025-07-13 21:36:11,060 - INFO - Loaded cog: leveling.py
2025-07-13 21:36:11,276 - INFO - Loaded cog: movies.py
2025-07-13 21:36:11,397 - INFO - Loaded cog: notification.py
2025-07-13 21:36:11,404 - INFO - Loaded cog: serverstat.py
2025-07-13 21:36:11,409 - INFO - Loaded cog: tournaments.py
2025-07-13 21:36:11,412 - INFO - Loaded cog: welcome.py
2025-07-13 21:36:11,414 - INFO - Loaded commands and cogs
2025-07-13 21:36:11,742 - INFO - Slash commands synced successfully: 33 commands
2025-07-13 21:36:13,945 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-13 21:36:14.079572:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:36:14,085 - ERROR - Exception occurred on 2025-07-13 21:36:14.079572:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:36:14.213167:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:36:14,216 - ERROR - Exception occurred on 2025-07-13 21:36:14.213167:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:36:14.401641:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:36:14,405 - ERROR - Exception occurred on 2025-07-13 21:36:14.401641:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:36:14.707035:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:36:14,710 - ERROR - Exception occurred on 2025-07-13 21:36:14.707035:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:36:14.855826:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:36:14,857 - ERROR - Exception occurred on 2025-07-13 21:36:14.855826:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:36:15.053500:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:36:15,055 - ERROR - Exception occurred on 2025-07-13 21:36:15.053500:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:44:48,897 - INFO - Loaded command: coinflip.py
2025-07-13 21:44:48,900 - INFO - Loaded command: ouroboros.py
2025-07-13 21:44:48,922 - INFO - Loaded command: rpsgame.py
2025-07-13 21:44:48,928 - INFO - Loaded command: rpsvs.py
2025-07-13 21:44:48,932 - INFO - Loaded command: sporty.py
2025-07-13 21:44:48,937 - INFO - Loaded command: update.py
2025-07-13 21:44:48,951 - INFO - Loaded cog: channelmanagement.py
2025-07-13 21:44:48,955 - INFO - Loaded cog: embed.py
2025-07-13 21:44:48,992 - INFO - Loaded cog: finance.py
2025-07-13 21:44:49,062 - INFO - Loaded cog: leaderboard.py
2025-07-13 21:44:50,629 - INFO - Loaded cog: leveling.py
2025-07-13 21:44:50,999 - INFO - Loaded cog: movies.py
2025-07-13 21:44:51,130 - INFO - Loaded cog: notification.py
2025-07-13 21:44:51,138 - INFO - Loaded cog: serverstat.py
2025-07-13 21:44:51,144 - INFO - Loaded cog: tournaments.py
2025-07-13 21:44:51,147 - INFO - Loaded cog: welcome.py
2025-07-13 21:44:51,149 - INFO - Loaded commands and cogs
2025-07-13 21:44:51,474 - INFO - Slash commands synced successfully: 33 commands
2025-07-13 21:44:53,725 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-13 21:44:53.890038:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:44:53,895 - ERROR - Exception occurred on 2025-07-13 21:44:53.890038:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:44:54.017020:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:44:54,021 - ERROR - Exception occurred on 2025-07-13 21:44:54.017020:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:44:54.144415:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:44:54,145 - ERROR - Exception occurred on 2025-07-13 21:44:54.144415:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:44:54.347344:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:44:54,350 - ERROR - Exception occurred on 2025-07-13 21:44:54.347344:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:44:54.524193:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:44:54,526 - ERROR - Exception occurred on 2025-07-13 21:44:54.524193:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:44:54.745300:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:44:54,747 - ERROR - Exception occurred on 2025-07-13 21:44:54.745300:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:59:06,993 - INFO - Loaded command: coinflip.py
2025-07-13 21:59:06,996 - INFO - Loaded command: ouroboros.py
2025-07-13 21:59:07,010 - INFO - Loaded command: rpsgame.py
2025-07-13 21:59:07,014 - INFO - Loaded command: rpsvs.py
2025-07-13 21:59:07,017 - INFO - Loaded command: sporty.py
2025-07-13 21:59:07,021 - INFO - Loaded command: update.py
2025-07-13 21:59:07,027 - INFO - Loaded cog: channelmanagement.py
2025-07-13 21:59:07,030 - INFO - Loaded cog: embed.py
2025-07-13 21:59:07,054 - INFO - Loaded cog: finance.py
2025-07-13 21:59:07,105 - INFO - Loaded cog: leaderboard.py
2025-07-13 21:59:08,683 - INFO - Loaded cog: leveling.py
2025-07-13 21:59:08,871 - INFO - Loaded cog: movies.py
2025-07-13 21:59:08,959 - INFO - Loaded cog: notification.py
2025-07-13 21:59:08,964 - INFO - Loaded cog: serverstat.py
2025-07-13 21:59:08,969 - INFO - Loaded cog: tournaments.py
2025-07-13 21:59:08,971 - INFO - Loaded cog: welcome.py
2025-07-13 21:59:08,972 - INFO - Loaded commands and cogs
2025-07-13 21:59:09,379 - INFO - Slash commands synced successfully: 33 commands
2025-07-13 21:59:11,629 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-13 21:59:11.759577:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:59:11,765 - ERROR - Exception occurred on 2025-07-13 21:59:11.759577:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:59:11.925636:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:59:11,927 - ERROR - Exception occurred on 2025-07-13 21:59:11.925636:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:59:12.108167:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 21:59:12,111 - ERROR - Exception occurred on 2025-07-13 21:59:12.108167:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 21:59:12.327746:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:59:12,332 - ERROR - Exception occurred on 2025-07-13 21:59:12.327746:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:59:12.472279:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:59:12,474 - ERROR - Exception occurred on 2025-07-13 21:59:12.472279:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 21:59:12.691183:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 21:59:12,693 - ERROR - Exception occurred on 2025-07-13 21:59:12.691183:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 22:00:57,306 - INFO - Loaded command: coinflip.py
2025-07-13 22:00:57,328 - INFO - Loaded command: ouroboros.py
2025-07-13 22:00:57,394 - INFO - Loaded command: rpsgame.py
2025-07-13 22:00:57,423 - INFO - Loaded command: rpsvs.py
2025-07-13 22:00:57,429 - INFO - Loaded command: sporty.py
2025-07-13 22:00:57,435 - INFO - Loaded command: update.py
2025-07-13 22:00:57,445 - INFO - Loaded cog: channelmanagement.py
2025-07-13 22:00:57,449 - INFO - Loaded cog: embed.py
2025-07-13 22:00:57,495 - INFO - Loaded cog: finance.py
2025-07-13 22:00:57,550 - INFO - Loaded cog: leaderboard.py
2025-07-13 22:00:58,940 - INFO - Loaded cog: leveling.py
2025-07-13 22:00:59,310 - INFO - Loaded cog: movies.py
2025-07-13 22:00:59,423 - INFO - Loaded cog: notification.py
2025-07-13 22:00:59,428 - INFO - Loaded cog: serverstat.py
2025-07-13 22:00:59,434 - INFO - Loaded cog: tournaments.py
2025-07-13 22:00:59,438 - INFO - Loaded cog: welcome.py
2025-07-13 22:00:59,439 - INFO - Loaded commands and cogs
2025-07-13 22:00:59,920 - INFO - Slash commands synced successfully: 33 commands
2025-07-13 22:01:03,456 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-13 22:01:03.599312:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 22:01:03,605 - ERROR - Exception occurred on 2025-07-13 22:01:03.599312:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 22:01:03.736240:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 22:01:03,738 - ERROR - Exception occurred on 2025-07-13 22:01:03.736240:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 22:01:03.851431:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-13 22:01:03,853 - ERROR - Exception occurred on 2025-07-13 22:01:03.851431:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-13 22:01:03.990494:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 22:01:03,995 - ERROR - Exception occurred on 2025-07-13 22:01:03.990494:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 22:01:04.141101:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 22:01:04,143 - ERROR - Exception occurred on 2025-07-13 22:01:04.141101:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-13 22:01:04.349870:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-13 22:01:04,350 - ERROR - Exception occurred on 2025-07-13 22:01:04.349870:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

